apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
  #ME_CONFIG_MONGODB_ADMINUSERNAME: 4oCTbiBteWV4cHJlc3N1c2VyCg==
  #ME_CONFIG_MONGODB_ADMINPASSWORD: 4oCTbiBteWV4cHJlc3NwYXNzCg==
